"""Add TimescaleDB chat session and message tables

Revision ID: add_timescaledb_chat_tables
Revises: e2412789c190
Create Date: 2025-01-11 13:00:00.000000

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
import uuid

# revision identifiers, used by Alembic.
revision = "add_timescaledb_chat_tables"
down_revision = "e2412789c190"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 创建会话表 (TimescaleDB 超表)
    op.create_table(
        "chatsession",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("system_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chatsession_user_id"), "chatsession", ["user_id"], unique=False)

    # 创建消息表 (TimescaleDB 超表)
    op.create_table(
        "chatmessage",
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("finish_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("model_used", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["chatsession.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chatmessage_session_id"), "chatmessage", ["session_id"], unique=False)

    # 启用 TimescaleDB 扩展（如果未启用）
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;")

    # 将表转换为 TimescaleDB 超表
    op.execute("SELECT create_hypertable('chatsession', 'created_at');")
    op.execute("SELECT create_hypertable('chatmessage', 'created_at');")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除超表
    op.execute("DROP TABLE IF EXISTS chatmessage;")
    op.execute("DROP TABLE IF EXISTS chatsession;")

    # ### end Alembic commands ###